.PHONY: help

plot:
	dot -Tpng $(INPUT) -o $(OUTPUT)
help:
	@echo "Usage: make [target]"
	@echo ""
	@echo "Available targets:"
	@echo "  plot     - generate a PNG image from input.dot"
	@echo "             EX: make plot [INPUT=input.dot] [OUTPUT=output.png]"
	@echo ""
